### ISSUE TITLE
What is "sat:orbit_state"?

### ISSUE THREAD

**Issue by LostGeorge** [iprapas/landslide-sar-unet#2]
[https://github.com/iprapas/landslide-sar-unet/blob/main/src/datamodule.py#L18](Here) in the data preprocessing, we filter by sat:orbit_state "d". It seems like sat:orbit_state can be either "a" or "d." What do these mean, and why do we filter by "d"?

**Comment by weiji14** [comment]
> https://github.com/iprapas/landslide-sar-unet/blob/main/src/datamodule.py#L18 in the data preprocessing, we filter by sat:orbit_state "d". It seems like sat:orbit_state can be either "a" or "d." What do these mean, and why do we filter by "d"?

The a and d stands for ascending and descending orbits of the Synthetic Aperture Radar satellite. I.e. images taken when the satellite is flying Northwards or flying Southwards. For certain locations on the Earth, the ascending pass image might not capture the entire area nicely, so we filtered those out and only keep the descending pass images. Hopefully this answers your question.
