### ISSUE TITLE
Model weights

### ISSUE THREAD

**Issue by cOsprey** [iprapas/landslide-sar-unet#3]
Can the model weights be made available for inferencing on hokkaido datacube ?

**Comment by iprapas** [comment]
The weights from the original experiments described in the paper have not been kept, but one could reproduce them with the available code in this repo. Without access to a gpu, a platform like google colab might be helpful.

**Comment by oguzhannysr** [comment]
@iprapas Hello, first of all, thank you.  My question is, how can I do model training in colab?  Then, do I only need the sar image in the descending orbit to test data in different locations?

**Comment by iprapas** [comment]
> @iprapas Hello, first of all, thank you.  My question is, how can I do model training in colab?  

I may be able to check this, but it will take some time as I am working on different stuff currently. If you manage to do it in the mean time please let me know!

> Then, do I only need the sar image in the descending orbit to test data in different locations?

Yes, or you can change this line to ascending orbit if you prefer https://github.com/iprapas/landslide-sar-unet/blob/main/src%2Fdatamodule.py#L19 another option would be to include ascending and descending orbits as different channels or find a way to merge them
